/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StorageFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createSimpleStorageContract()": FunctionFragment;
    "sfGet(uint256,uint256)": FunctionFragment;
    "sfStore(uint256,uint256)": FunctionFragment;
    "simpleStorageArray(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createSimpleStorageContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sfGet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sfStore",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simpleStorageArray",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSimpleStorageContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sfGet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sfStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simpleStorageArray",
    data: BytesLike
  ): Result;

  events: {};
}

export class StorageFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StorageFactoryInterface;

  functions: {
    createSimpleStorageContract(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createSimpleStorageContract()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sfGet(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sfGet(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sfStore(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "sfStore(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    simpleStorageArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "simpleStorageArray(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createSimpleStorageContract(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createSimpleStorageContract()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sfGet(
    _simpleStorageIndex: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sfGet(uint256,uint256)"(
    _simpleStorageIndex: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sfStore(
    _simpleStorageIndex: BigNumberish,
    _simpleStorageNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "sfStore(uint256,uint256)"(
    _simpleStorageIndex: BigNumberish,
    _simpleStorageNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  simpleStorageArray(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "simpleStorageArray(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createSimpleStorageContract(overrides?: CallOverrides): Promise<void>;

    "createSimpleStorageContract()"(overrides?: CallOverrides): Promise<void>;

    sfGet(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sfGet(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sfStore(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sfStore(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    simpleStorageArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "simpleStorageArray(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createSimpleStorageContract(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createSimpleStorageContract()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sfGet(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sfGet(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sfStore(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "sfStore(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    simpleStorageArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "simpleStorageArray(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createSimpleStorageContract(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createSimpleStorageContract()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sfGet(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sfGet(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sfStore(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "sfStore(uint256,uint256)"(
      _simpleStorageIndex: BigNumberish,
      _simpleStorageNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    simpleStorageArray(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "simpleStorageArray(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
